# Use a minimal and secure official NGINX image
FROM nginx:stable-alpine

# Set working directory
WORKDIR /app

# Copy necessary from the local 'files' directory into the container
COPY files/etc/nginx/ /etc/nginx/
COPY files/var/www/html/ /var/www/html/
COPY files/entrypoint_nginx.sh /app/.
COPY files/entrypoint_k8s_nginx.sh /app/.
RUN mkdir -p /etc/nginx/sites-enabled

# Set the entrypoint
ENTRYPOINT ["/app/entrypoint_k8s_nginx.sh"]
