# Use a minimal and secure official NGINX image
FROM nginxinc/nginx-unprivileged:stable-alpine

# Add bash used by entrypoint scripts
RUN apk add --no-cache bash

# Set working directory
WORKDIR /app

# Copy necessary from the local 'files' directory into the container
COPY --chown=101:0 --chmod=0755 files/etc/nginx/ /etc/nginx/
COPY --chown=101:0 --chmod=0755 files/var/www/html/ /var/www/html/
COPY --chown=101:0 --chmod=0550 files/entrypoint_nginx.sh /app/.
COPY --chown=101:0 --chmod=0550 files/entrypoint_k8s_nginx.sh /app/.

#DEBUG
RUN echo "Listing /app:" && ls -la /app && \
    echo "Listing /etc/nginx:" && ls -la /etc/nginx && \
    echo "Listing /var/www/html:" && ls -la /var/www/html

# Set the entrypoint
ENTRYPOINT ["bash", "/app/entrypoint_k8s_nginx.sh"]

# Use a non-root user (already set in nginx-unprivileged image)
USER 101
